/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as WatchesIndexRouteImport } from './routes/watches.index'
import { Route as WatchesWatchIdRouteImport } from './routes/watches.$watchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchesIndexRoute = WatchesIndexRouteImport.update({
  id: '/watches/',
  path: '/watches/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchesWatchIdRoute = WatchesWatchIdRouteImport.update({
  id: '/watches/$watchId',
  path: '/watches/$watchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/watches/$watchId': typeof WatchesWatchIdRoute
  '/watches/': typeof WatchesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/watches/$watchId': typeof WatchesWatchIdRoute
  '/watches': typeof WatchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/watches/$watchId': typeof WatchesWatchIdRoute
  '/watches/': typeof WatchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create' | '/watches/$watchId' | '/watches/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create' | '/watches/$watchId' | '/watches'
  id: '__root__' | '/' | '/create' | '/watches/$watchId' | '/watches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  WatchesWatchIdRoute: typeof WatchesWatchIdRoute
  WatchesIndexRoute: typeof WatchesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/': {
      id: '/watches/'
      path: '/watches'
      fullPath: '/watches/'
      preLoaderRoute: typeof WatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watches/$watchId': {
      id: '/watches/$watchId'
      path: '/watches/$watchId'
      fullPath: '/watches/$watchId'
      preLoaderRoute: typeof WatchesWatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  WatchesWatchIdRoute: WatchesWatchIdRoute,
  WatchesIndexRoute: WatchesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
