/**
 * Information produced by the planning/reasoning stage
 * and used to generate a scraper.
 */
export interface ScraperTarget {
  url: string;
  title: string;
  instructions: string[];
  evidenceRequirements: string[];
}

/**
 * User-facing schema proposal generated by Bright Data
 * Scraper Studio / AI Flow.
 */
export interface ScraperSchema {
  name: string;
  description?: string;
  fields: ScraperField[];
}

/**
 * A single field extracted by the scraper.
 */
export interface ScraperField {
  name: string;
  type: ScraperFieldType;
  description: string;
  required: boolean;
}

export type ScraperFieldType =
  | "string"
  | "number"
  | "boolean"
  | "date"
  | "array"
  | "object";

/**
 * Application-level scraper lifecycle.
 */
export type ScraperStatus =
  | "PENDING"
  | "CREATING"
  | "AI_FLOW_RUNNING"
  | "REVIEW_REQUIRED"
  | "APPROVED"
  | "READY"
  | "RUNNING"
  | "COMPLETED"
  | "FAILED"
  | "UNAVAILABLE";

export interface ScraperApprovalRequest {
  schema: ScraperSchema;
}

export interface CreateCollectorRequest {
  target: ScraperTarget;
  schema: ScraperSchema;
}

export interface Collector {
  collectorId: string;
  name: string;
  url: string;
  status: CollectorStatus;
}

export type CollectorStatus =
  | "CREATED"
  | "READY"
  | "RUNNING"
  | "COMPLETED"
  | "FAILED";

export interface RunCollectorRequest {
  collectorId: string;
}

export interface AiFlowProgress {
  status: string;
  step?: string;
  completedSteps?: string[];

  schema?: unknown;
  sampleData?: unknown;
  template?: unknown;

  [key: string]: unknown;
}

export interface AiFlowTriggerResult {
  jobId: string;
  queued: boolean;
}

export interface CollectorTriggerResult {
  collectionId: string;
}

export interface CollectorResult {
  collectorId: string;
  status: "COMPLETED" | "FAILED";
  data: Record<string, unknown>[];
  collectedAt: string;
}

export interface ScraperGenerationResult {
  target: ScraperTarget;
  schema?: ScraperSchema;
  collectorId: string;
  aiJobId: string;
  sampleData?: Record<string, unknown>[];
  status: ScraperStatus;
}

export interface ScraperState {
  target: ScraperTarget;
  schema?: ScraperSchema;
  collector?: Collector;
  generation?: ScraperGenerationResult;
  latestResult?: CollectorResult;
}
